### ISSUE TITLE
Margins of collapsed panel's titles cease to exist in firefox (works fine in chrome)

### ISSUE THREAD

**Issue by brazadas** [datasketch/shinypanels#69]
![Screenshot from 2020-04-29 13-47-14](https://user-images.githubusercontent.com/19413995/80634580-4afe7c80-8a20-11ea-9580-7c7bdf6e49ac.png)

**Comment by brazadas** [comment]
@ddazal @CamilaAchury hola

**Comment by ddazal** [comment]
@brazadas Adiós
