### ISSUE TITLE
Fix panel internal width

### ISSUE THREAD

**Issue by jpmarindiaz** [datasketch/shinypanels#73]
A horizontal scroll bar appears when not needed
![image](https://user-images.githubusercontent.com/1489570/83165042-99ac3e80-a0d2-11ea-8a9e-651a2c41a2b4.png)

**Comment by brazadas** [comment]
this horizontal scroll is actually because of the info tooltip that is not overlapping the panel but it is staying inside overflowing it (issue #43 parmesan) ; we have been looking at it with @ddazal

**Comment by jpmarindiaz** [comment]
I don't see why it is related to changing the panel size. 
No need to augment the panel size with the size of the tooltip. The tooltip should stay within the defined limits of the panel

**Comment by brazadas** [comment]
there is no manual change in the panel size; it an undesired behavior due to the overflow-y property of the panel-body class (where the info tooltips lay). We haven't been able to figure it out why it affects the overflow-x property but it does. @ddazal and I are still trying to figure it out
