### ISSUE TITLE
shiny's tabsetPanel not working with shinypanels

### ISSUE THREAD

**Issue by brazadas** [datasketch/shinypanels#76]
It seems like shinypanels styles are overriding shiny's tabsetPanel; when using tabsetPanel inside shinypanels' panelsPage this is what you expect:
![Screenshot from 2020-06-17 11-38-35](https://user-images.githubusercontent.com/19413995/84925406-73edd600-b08f-11ea-8c55-aef54838dab2.png)
and this is what you get
![Screenshot from 2020-06-17 11-39-06](https://user-images.githubusercontent.com/19413995/84925383-6b959b00-b08f-11ea-9bca-0dd8cbf9bd66.png)

**Comment by jpmarindiaz** [comment]
I don't think we will be implementing our own tabs for shinypanels anytime soon. 
Can you mimic the behavior with 2 regular buttons?
When clicked they show the contents of the corresponding div and hide the other.

**Comment by brazadas** [comment]
inside the app?
yes

**Comment by brazadas** [comment]
but ... isn't it a matter of adjusting the style sheet?

**Comment by jpmarindiaz** [comment]
No, because shinypanels does not depend on bootstrap

**Comment by brazadas** [comment]
a ok
