### ISSUE TITLE
Not being able to align panel title with download dropdown button

### ISSUE THREAD

**Issue by brazadas** [datasketch/shinypanels#77]
I haven't been able to align the dropdown button with the panel's title as in the design:
![Screenshot from 2020-07-08 17-26-24](https://user-images.githubusercontent.com/19413995/86976515-39cc9d00-c140-11ea-9846-26e6051e57d2.png)

So it's looking like this

![Screenshot from 2020-07-08 17-25-18](https://user-images.githubusercontent.com/19413995/86976688-9fb92480-c140-11ea-9c12-e8662fae9c4c.png)

**Comment by brazadas** [comment]
@ddazal

**Comment by jpmarindiaz** [comment]
@CamilaAchury creo que ya lo solucionó revisa los commits anteriores

**Comment by brazadas** [comment]
Sí perfecto, gracias!

**Comment by jpmarindiaz** [comment]
@CamilaAchury @brazadas no olviden cerrar issues si solucionan algo
