### ISSUE TITLE
should headers and footers be always visible (sticky)?

### ISSUE THREAD

**Issue by brazadas** [datasketch/shinypanels#91]
See options panel:

![Screenshot from 2020-08-31 22-19-46](https://user-images.githubusercontent.com/19413995/91791274-51705100-ebd8-11ea-8f3d-7ca7bfaa1b44.png)
![Screenshot from 2020-08-31 22-19-44](https://user-images.githubusercontent.com/19413995/91791281-58975f00-ebd8-11ea-9dca-aed2c9d89202.png)

**Comment by jpmarindiaz** [comment]
I think so, they should be sticky
